<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-T9AMV25E" failures="1" tests="9" name="Default test" time="70.218" errors="0" timestamp="2024-12-04T12:15:48 IST">
  <testcase classname="com.parabank.testcases.TC_RegisterCustomerTest" name="verifyAppLaunch" time="7.642"/>
  <testcase classname="com.parabank.testcases.TC_RegisterCustomerTest" name="verifyRegistration" time="8.026"/>
  <testcase classname="com.parabank.testcases.TC_RegisterCustomerTest" name="verifyLogOut" time="1.982"/>
  <testcase classname="com.parabank.testcases.TC_RegisterCustomerTest" name="verifyLogin" time="4.363"/>
  <testcase classname="com.parabank.testcases.TC_RegisterCustomerTest" name="verifyInitialAccountDetails" time="3.519"/>
  <testcase classname="com.parabank.testcases.TC_RegisterCustomerTest" name="verifyOpenNewAccount" time="12.613"/>
  <testcase classname="com.parabank.testcases.TC_RegisterCustomerTest" name="verifyFundsTransfer" time="8.719"/>
  <testcase classname="com.parabank.testcases.TC_RegisterCustomerTest" name="verifyBillPayment" time="11.45"/>
  <testcase classname="com.parabank.testcases.TC_RegisterCustomerTest" name="verifyFindTransactionsAPI" time="5.066">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at com.parabank.testcases.TC_RegisterCustomerTest.verifyFindTransactionsAPI(TC_RegisterCustomerTest.java:193)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyFindTransactionsAPI -->
</testsuite> <!-- Default test -->
